### ISSUE TITLE
[feature] demo in python

### ISSUE THREAD

**Issue by edwardsun** [openctp/webctp#41]
您好，
请问有没有可能在这个项目里用python做一个简单的demo? 最好包括登录，获取合约信息，获取用户信息之类的。
非常感谢

**Comment by DennisXie** [comment]
这个项目实际上主要是为了对接前端，Python的话你可以考虑直接使用Python API会更加简单。

**Comment by edwardsun** [comment]
> 这个项目实际上主要是为了对接前端，Python的话你可以考虑直接使用Python API会更加简单。

您好，
感谢回复。

我可以简单描述一下use case:

一个本地的restful api service：
启动的时候：配置阶段，记录 登录名/用户密码/行情服务器等，最好能支持断线重连。此时账号已经和服务绑定

主要功能：查询账号资金，持仓，支持下单，针对各请求返回相应内容。不需要异步，对速度也没有特别的需求。
平时交易的时候，一般是每天开盘的时候下一个fill-and-kill单子就行，不在乎成交价。

注意到启动功能和主要功能差别较大，python api貌似不能剥离两者。因此觉得webctp项目好像是一个很好的选择。

不知道这种使用案例是否合适webctp？
感谢。

**Comment by DennisXie** [comment]
目前这个项目没有打算提供restful API，restful API的语义是操作资源，但是CTP API是一种命令，webctp也只是对CTP API进行了websocket协议的封装。所以两者在语义上有区别。另外restful API一般来说是一个http request, 然后就会得到一个http response，但是CTP的一条指令可能会得到很多响应，比如一个成功的下单指令，至少会得到3条相关的响应。如果你懂react的话可以看一下我去年写的前端demo，没有readme，但是也不算难。https://github.com/DennisXie/webctp-demo

**Comment by edwardsun** [comment]
> 目前这个项目没有打算提供restful API，restful API的语义是操作资源，但是CTP API是一种命令，webctp也只是对CTP API进行了websocket协议的封装。所以两者在语义上有区别。另外restful API一般来说是一个http request, 然后就会得到一个http response，但是CTP的一条指令可能会得到很多响应，比如一个成功的下单指令，至少会得到3条相关的响应。如果你懂react的话可以看一下我去年写的前端demo，没有readme，但是也不算难。https://github.com/DennisXie/webctp-demo

我还是试试openctp python吧。
感谢回复。
