### ISSUE TITLE
按教程无法启动ws  403 错误

### ISSUE THREAD

**Issue by PPsteven** [openctp/webctp#42]
配置文件后运行：python main.py --config=config_td.yaml --app_type=td
项目运行
$ python main.py --config=config_td.yaml --app_type=td
2024-11-01 03:15:17,678 - root - INFO - start td app
INFO:     Started server process [4030]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8882 (Press CTRL+C to quit)

客户端连接  报错 403
$ python -m websockets ws://0.0.0.0:8882/td
Failed to connect to ws://0.0.0.0:8882/td: server rejected WebSocket connection: HTTP 403.

此时服务端收到
INFO:     ('127.0.0.1', 62736) - "WebSocket /td" 403
INFO:     connection rejected (403 Forbidden)
INFO:     connection closed

综上，应该是403 的错误，但是检测了 路径，应该也是没有问题，对ws开发不太熟悉，完全按照教程运行，但是卡在这一步无法继续

**Comment by Jedore** [comment]
客户端连接 127.0.0.1 试试 @PPsteven

**Comment by DennisXie** [comment]
我印象中要127.0.0.1:8802/td/发自我的 iPhone在 2024年11月1日，07:48，Jedore ***@***.***> 写道：﻿
客户端连接 127.0.0.1 试试 @PPsteven

**Comment by PPsteven** [comment]
原因已找到：尾部需要添加 /
```bash
$ python -m websockets ws://127.0.0.1:8881/md/
Connected to ws://127.0.0.1:8881/md/.
> {"MsgType":"ReqUserLogin","ReqUserLogin":{"UserID":"111","Password":"000000"}}
```
感觉 @DennisXie 和 @Jedore 的回答，希望也可以补充在文档中稍微完善下
